spring:
  application:
    name: FirstRestAplication
  datasource:
    url: jdbc:postgresql://localhost:5432/crudDB
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

server:
  port : 8080




